#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=16,walltime=01:00:00

tck_id=`jq -r '._inputs[0].meta.subject' config.json`
t1_id=`jq -r '._inputs[1].meta.subject' config.json`
mask_id=`jq -r '._inputs[2].meta.subject' config.json`

echo "Check the inputs subject id"
if [ $mask_id == null ]; then
	if [ $tck_id == $t1_id ]; then
		echo "Inputs subject IDs correctly inserted"
	else
		echo "Inputs subject IDs incorrectly inserted. Check them again."
		exit 1
	fi
else
	if [ $tck_id == $t1_id -a $tck_id == $mask_id ]; then
		echo "Inputs subject IDs correctly inserted"
	else
		echo "Inputs subject IDs incorrectly inserted. Check them again."
		exit 1
	fi
fi

mkdir -p warps
mkdir -p warp_dir
mkdir -p track_aligned
mkdir -p t1_aligned

tck=`jq -r '.track' config.json`
t1=`jq -r '.t1' config.json`

echo "Computing warp to MNI space..."
singularity exec -e docker://giuliaberto/ants2-mrtrix3-fsl6:1.1 ./run_registration.sh $t1 $tck

ret=$?
if [ ! $ret -eq 0 ]; then
	exit $ret
fi

echo "Complete"